/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.sql.*;
import br.com.Conexao.FazendoConexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//importa os recursos da biblioteca re2xml.jar
import net.proteanit.sql.DbUtils;
/**
 *
 * @author gabri
 */
public class BaseProdutos extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    AlterarProduto produto;
    /**
     * Creates new form BaseProdutos
     */
    public BaseProdutos() {
        initComponents();
        conexao = FazendoConexao.conector();
    }
    
    public void Busca_Produtos() {
        String sqlBusca = "select idVinho, NomeProduto, Preco from produtos  where NomeProduto like ? ";
        try {
            pst = conexao.prepareStatement(sqlBusca);
            //passando o conteudo da caixa de pesquisa para o interroga 
            //atencao ao % que é a continuacao da string busca sql
            pst.setString(1, buscarProduto.getText() + "%");
            rs = pst.executeQuery();
            //a linha abaixo usa a biblioteca para preeencher a tabela
            tabelaProdutos.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * Esse metódo irá passar o indice do produto selecionado para poder alterar
     */
    public void setar_campos(){
        //pega o id do produto na tabela 
        int indiceTabela = tabelaProdutos.getSelectedRow();
                
        if(indiceTabela == -1){
            //ou seja não há nenhum produto selecionado 
            JOptionPane.showMessageDialog(null, "Por favor selecione um produto para editar.");
        }else{
            //pegando o indice do cliente selecionado
            String indiceProduto  = tabelaProdutos.getModel().getValueAt(indiceTabela, 0).toString();
        
            
            produto = new AlterarProduto();
            Tela_Principal.fundoArea.add(produto);
            produto.setVisible(true);
            produto.recebendoDados(indiceProduto);
        }
    } 
    
    private void RemovendoProduto(){
        //pega o id do Cliente na tabela 
        int indiceTabela = tabelaProdutos.getSelectedRow();
        if(indiceTabela == -1){
            //ou seja não há nenhum cliente selecionado 
            JOptionPane.showMessageDialog(null, "Por favor selecione um produto para remover.");
        }else{
            
            //pegando o indice do produto selecionado
            String indiceProduto  = tabelaProdutos.getModel().getValueAt(indiceTabela, 0).toString();
            
            //caixa de dialogo para confirmar se realmente quer excluir o cliente
            int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o produto selecionado ?","Atenção",JOptionPane.YES_NO_OPTION);
            //excluindo cliente do banco de dados
            if (confirma == JOptionPane.YES_OPTION) {
                String sql = "delete from produtos where idVinho = ?";
                try {
                    pst = conexao.prepareStatement(sql);
                    pst.setString(1, indiceProduto);
                    int apagado = pst.executeUpdate();
                    
                    if(apagado > 0){
                        JOptionPane.showMessageDialog(null, "Produto excluído com sucesso !");
                        
                        //Removendo a linha da tabela
                        DefaultTableModel dtmProdutos = (DefaultTableModel) tabelaProdutos.getModel();
                        dtmProdutos.removeRow(indiceTabela);
                    }
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscarProduto = new javax.swing.JTextField();
        btnBuscarProduto = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        btnExcluirProduto = new javax.swing.JButton();
        btnEditarProduto = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Le Vin - Tela Produtos");

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        buscarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarProdutoKeyReleased(evt);
            }
        });

        btnBuscarProduto.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarProduto.setForeground(new java.awt.Color(0, 204, 255));
        btnBuscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-magnifier.png"))); // NOI18N
        btnBuscarProduto.setText("Buscar");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        btnCadastrarProduto.setBackground(new java.awt.Color(102, 102, 102));
        btnCadastrarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadastrarProduto.setForeground(new java.awt.Color(0, 204, 255));
        btnCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MaisAzul.png"))); // NOI18N
        btnCadastrarProduto.setText("Cadastrar");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(buscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarProduto)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabelaProdutos = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex ){
                return false;
            }
        };
        tabelaProdutos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCliente", "Nome", "Email", "Perfil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setRowHeight(26);
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        btnExcluirProduto.setBackground(new java.awt.Color(102, 102, 102));
        btnExcluirProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirProduto.setForeground(new java.awt.Color(0, 204, 255));
        btnExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        btnExcluirProduto.setText("Excluir");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        btnEditarProduto.setBackground(new java.awt.Color(102, 102, 102));
        btnEditarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditarProduto.setForeground(new java.awt.Color(0, 204, 255));
        btnEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alterar.png"))); // NOI18N
        btnEditarProduto.setText("Editar");
        btnEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        Busca_Produtos();
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        RemovendoProduto();
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        CadastroProduto telaCadastroProdutos = new CadastroProduto();
        Tela_Principal.fundoArea.add(telaCadastroProdutos);
        telaCadastroProdutos.setVisible(true);
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdutoActionPerformed
        setar_campos();
    }//GEN-LAST:event_btnEditarProdutoActionPerformed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        //pegar dados com dois clicks
        if (evt.getClickCount() == 2 && evt.getButton() == evt.BUTTON1) {
            setar_campos();
        }
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void buscarProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarProdutoKeyReleased
        Busca_Produtos();
    }//GEN-LAST:event_buscarProdutoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnEditarProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JTextField buscarProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
