/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.*;
import br.com.Conexao.FazendoConexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//importa recursos da biblioteca rx2ml.jar
import net.proteanit.sql.DbUtils;

/**
 *
 * @author gabri
 */
public class BaseVendedores extends javax.swing.JInternalFrame {

    AlterarVendedor passaIndice;
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Vendedores
     */
    public BaseVendedores() {
        initComponents();
        conexao = FazendoConexao.conector();
    }

    /**
     * Este metodo faz a busca dos vendedores no banco de dados
     */
    private void Busca_Vendedores() {
        String sqlBusca = "select idVendedor, Nome, telefone,Perfil from vendedores  where Nome like ? ";
        try {
            pst = conexao.prepareStatement(sqlBusca);
            //passando o conteudo da caixa de pesquisa para o interroga 
            //atencao ao % que é a continuacao da string busca sql
            pst.setString(1, buscarVendedores.getText() + "%");
            rs = pst.executeQuery();
            //a linha abaixo usa a biblioteca para preeencher a tabela
            tabelaVendedores.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }

    }

    /**
     * Este metodo remove o vendedor selecionado da tabela
     */
    private void Removendo_Vendedor() {
        //pega o id do Cliente na tabela 
        int indiceTabela = tabelaVendedores.getSelectedRow();

        if (indiceTabela == -1) {
            //ou seja não há nenhum cliente selecionado 
            JOptionPane.showMessageDialog(null, "Por favor selecione um vendedor para remover.");
        } else {

            //pegando o indice do vendedor selecionado
            String indiceVendedor = tabelaVendedores.getModel().getValueAt(indiceTabela, 0).toString();

            //caixa de dialogo para confirmar se realmente quer excluir o vendedor
            int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o vendedor selecionado ?", "Atenção", JOptionPane.YES_NO_OPTION);

            //excluindo vendedor do banco de dados
            if (confirma == JOptionPane.YES_OPTION) {
                String sql = "delete from vendedores where idVendedor = ?";
                try {
                    pst = conexao.prepareStatement(sql);
                    pst.setString(1, indiceVendedor);
                    int apagado = pst.executeUpdate();

                    if (apagado > 0) {
                        JOptionPane.showMessageDialog(null, "Vendedor excluído com sucesso !");

                        //Removendo a linha da tabela
                        DefaultTableModel dtmProdutos = (DefaultTableModel) tabelaVendedores.getModel();
                        dtmProdutos.removeRow(indiceTabela);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }

    /**
     * Esse metódo irá passar o indice do vendedor selecionado para poder
     * alterar
     */
    public void setar_campos() {
        //pega o id do Vendedor na tabela 
        int indiceTabela = tabelaVendedores.getSelectedRow();

        if (indiceTabela == -1) {
            //ou seja não há nenhum vendedor selecionado 
            JOptionPane.showMessageDialog(null, "Por favor selecione um vendedor para editar.");
        } else {
            //pegando o indice do cliente selecionado
            String indiceVendedor = tabelaVendedores.getModel().getValueAt(indiceTabela, 0).toString();

            passaIndice = new AlterarVendedor();
            Tela_Principal.fundoArea.add(passaIndice);
            passaIndice.setVisible(true);
            passaIndice.recebendoDados(indiceVendedor);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscarVendedores = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendedores = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setResizable(true);
        setTitle("Le Vin - Tela Vendedores");
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        buscarVendedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarVendedoresKeyReleased(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 204, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-magnifier.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(102, 102, 102));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(0, 204, 255));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MaisAzul.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(buscarVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabelaVendedores = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex ){
                return false;
            }
        };
        tabelaVendedores.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCliente", "Nome", "Email", "Perfil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaVendedores.setRowHeight(26);
        tabelaVendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVendedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVendedores);

        btnExcluir.setBackground(new java.awt.Color(102, 102, 102));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(0, 204, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(102, 102, 102));
        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 204, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alterar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Busca_Vendedores();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Removendo_Vendedor();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        CadastroVendedor telaCadastroVendedor = new CadastroVendedor();
        Tela_Principal.fundoArea.add(telaCadastroVendedor);
        telaCadastroVendedor.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        setar_campos();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tabelaVendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVendedoresMouseClicked
        //pegar dados com dois clicks
        if (evt.getClickCount() == 2 && evt.getButton() == evt.BUTTON1) {
            setar_campos();
        }
    }//GEN-LAST:event_tabelaVendedoresMouseClicked

    private void buscarVendedoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarVendedoresKeyReleased
        Busca_Vendedores();
    }//GEN-LAST:event_buscarVendedoresKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JTextField buscarVendedores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVendedores;
    // End of variables declaration//GEN-END:variables
}
